// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfQ6D2CP7UlnKsziKWWCevQjYKVWHKKFo',
    appId: '1:803838735327:web:15eb17b7eecc1320b7ca6a',
    messagingSenderId: '803838735327',
    projectId: 'raghay-1a172',
    authDomain: 'raghay-1a172.firebaseapp.com',
    storageBucket: 'raghay-1a172.firebasestorage.app',
    measurementId: 'G-W2CQDSQ2Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcoCwdR4E5-SzCPMiAJbxq1cGY589sjpU',
    appId: '1:803838735327:android:125a024e4fe50afcb7ca6a',
    messagingSenderId: '803838735327',
    projectId: 'raghay-1a172',
    storageBucket: 'raghay-1a172.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMtEcwDb1-vO7NjuqGRkYKZhlotwY5pM',
    appId: '1:803838735327:ios:9dd846e691537f72b7ca6a',
    messagingSenderId: '803838735327',
    projectId: 'raghay-1a172',
    storageBucket: 'raghay-1a172.firebasestorage.app',
    iosBundleId: 'com.example.raghayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMtEcwDb1-vO7NjuqGRkYKZhlotwY5pM',
    appId: '1:803838735327:ios:9dd846e691537f72b7ca6a',
    messagingSenderId: '803838735327',
    projectId: 'raghay-1a172',
    storageBucket: 'raghay-1a172.firebasestorage.app',
    iosBundleId: 'com.example.raghayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfQ6D2CP7UlnKsziKWWCevQjYKVWHKKFo',
    appId: '1:803838735327:web:4c80a023e6255253b7ca6a',
    messagingSenderId: '803838735327',
    projectId: 'raghay-1a172',
    authDomain: 'raghay-1a172.firebaseapp.com',
    storageBucket: 'raghay-1a172.firebasestorage.app',
    measurementId: 'G-8GZL1F4747',
  );
}
